<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TATRC-17323" ignored="0" name="Admin - Simulation - Personnel - Add/Edit/Delete/ErrorCheck" tests="1" failures="1" timestamp="07 Nov 2019 13:19:09 GMT" time="38.73" errors="0">
  <testcase name="execute" time="37.861" classname="testCases.Admin.Simulation.PersonnelAddEditDelete">
    <failure type="java.lang.AssertionError" message="Errors - Personnel Already Exists expected [Personnel already exists.] but found []">
      <![CDATA[java.lang.AssertionError: Errors - Personnel Already Exists expected [Personnel already exists.] but found []
	at testCases.Admin.Simulation.PersonnelAddEditDelete.performErrorValidation(PersonnelAddEditDelete.java:202)
	at testCases.Admin.Simulation.PersonnelAddEditDelete.execute(PersonnelAddEditDelete.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- execute -->
</testsuite> <!-- Admin - Simulation - Personnel - Add/Edit/Delete/ErrorCheck -->
